---
server:
    servlet:
        context-path: /appMis
        session:
            timeout: 12000 #单位：秒, 注：冒号后要有英文空格，要用TAb键缩格书写，表示层级！！！
    port: 8888

##在application.yml里面添加这句话,Grails3 上传文件访问 (需要添加static）可以不用static
grials:
    resources:
        pattern: /**
    cors:
        enabled: true   
   


grails:
    profile: web
    codegen:
        defaultPackage: appMis
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 15309923872


environments:
    development:
        dataSource:
            dbCreate: update
            #url: jdbc:mysql://192.168.17.30:3306/salarymis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
            url: jdbc:mysql://localhost:3306/appMis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
            dialect : org.hibernate.dialect.MySQL5InnoDBDialect

    test:
        dataSource:
            dbCreate: update
            #url: jdbc:mysql://192.168.17.30:3306/salarymis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
            url: jdbc:mysql://localhost:3306/appMis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
            dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    production:
        dataSource:
            dbCreate: update
            #url: jdbc:mysql://192.168.17.30:3306/salarymis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
            url: jdbc:mysql://localhost:3306/appMis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
            dialect : org.hibernate.dialect.MySQL5InnoDBDialect
            properties:
                jmxEnabled: true
                initialSize: 10
                maxActive: 100
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
